# Dockerfile
FROM python:3.9-slim

# RUN apt-get update \
#   && apt-get install -y build-essential

RUN apt-get update \
  && apt-get upgrade \ 
  && apt-get install -y build-essential

RUN pip install --upgrade pip
RUN pip install --upgrade setuptools

RUN pip install poetry